include:
  - project: 'we-private/backend/common-ci'
    ref: ci
    file: 'ci-functions/build_image.yml'
  - project: 'we-private/backend/common-ci'
    ref: ci
    file: 'ci-functions/deploy_stages.yml'
  - project: 'we-private/backend/common-ci'
    ref: ci
    file: 'ci-functions/migrations.yml'

variables:
  APP_NAME: updates-provider
  DB_NAME: websocket_x
  MIGRATION_UP_CMD: /usr/www/app/diesel migration run
  MIGRATION_DOWN_CMD: /usr/www/app/diesel migration redo

stages:
  - "Build docker image"
  - "Deploy to stage/test/dev"
  - "Migrations-INIT"
  - "Migrations-UP"
  - "Migrations-DOWN"
