[package]
name = "updates-provider"
version = "1.4.0"
authors = ["–êleksej Petrov <apetrov@wavesplatform.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
async-trait = "0.1"
envy = "0.4"
futures = "0.3"
itertools = "0.10"
r2d2 = "0.8"
r2d2_redis = "0.14"
reqwest = "0.11"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
tokio = { version = "1.5", features = ["macros", "rt-multi-thread"] }
url = "2.2"
percent-encoding = "2.1"
waves-protobuf-schemas = { git = "https://github.com/wavesplatform/protobuf-schemas", rev = "44b306885be296bbfebcd37bef64b4dbbec8502a" }
tonic = "0.5"
sha3 = "0.8"
blake2 = "0.9"
bs58 = "0.3"
diesel = { version = "1.4.5", features = ["postgres", "r2d2", "chrono", "numeric", "serde_json"] }
prost = "0.8"
prometheus = "0.12"
lazy_static = "1.4"
regex = "1.5"
warp = "0.3"
wavesexchange_log = { git = "https://github.com/waves-exchange/wavesexchange-rs", tag = "wavesexchange_log/0.4.0" }
wavesexchange_warp = { git = "https://github.com/waves-exchange/wavesexchange-rs", tag = "wavesexchange_warp/0.12.1" }
wavesexchange_topic = { git = "https://github.com/waves-exchange/wavesexchange-rs", tag = "wavesexchange_topic/0.2.1" }

[[bin]]
name = "service"
path = "src/main.rs"