ALTER TABLE data_entries ADD COLUMN key_frag_0 VARCHAR DEFAULT NULL;
ALTER TABLE data_entries ADD COLUMN key_frag_1 VARCHAR DEFAULT NULL;
ALTER TABLE data_entries ADD COLUMN key_frag_2 VARCHAR DEFAULT NULL;
ALTER TABLE data_entries ADD COLUMN key_frag_3 VARCHAR DEFAULT NULL;
ALTER TABLE data_entries ADD COLUMN key_frag_4 VARCHAR DEFAULT NULL;
ALTER TABLE data_entries ADD COLUMN key_frag_5 VARCHAR DEFAULT NULL;
ALTER TABLE data_entries ADD COLUMN key_frag_6 VARCHAR DEFAULT NULL;
ALTER TABLE data_entries ADD COLUMN key_frag_7 VARCHAR DEFAULT NULL;
