-- Your SQL goes here
CREATE TABLE IF NOT EXISTS blocks_microblocks (
    uid BIGINT GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT blocks_microblocks_uid_key
            UNIQUE,
    id VARCHAR NOT NULL
        CONSTRAINT blocks_microblocks_pkey
            PRIMARY KEY,
    height INTEGER NOT NULL,
    time_stamp BIGINT
);

CREATE INDEX IF NOT EXISTS blocks_microblocks_id_idx
    ON blocks_microblocks (id);

CREATE INDEX IF NOT EXISTS blocks_microblocks_time_stamp_uid_idx
    ON blocks_microblocks (time_stamp DESC, uid DESC);

CREATE TABLE IF NOT EXISTS transactions (
    block_uid BIGINT NOT NULL
        CONSTRAINT transactions_block_uid_fkey
            REFERENCES blocks_microblocks (uid)
                ON DELETE CASCADE,
    id VARCHAR CONSTRAINT transactions_id_key PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS recipients (
    uid BIGINT GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT recipients_uid_key
            PRIMARY KEY,
    address VARCHAR,
    transaction_id VARCHAR not null references transactions (id)
);

CREATE INDEX IF NOT EXISTS recipients_address_idx ON recipients (address);
